import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Alex Mandrila</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <h1 className={styles.titleTop}>Alex Mandrila</h1>
        
        <div className={styles.pisica}></div>
        <div className={styles.circle}></div>
        <div className={styles.curtain}></div>
      </main>
{/* 
      <footer className={styles.footer}>
       
      </footer> */}
      {/* Use an event listener on the mouse and move a mask over pisica image */}
    </div>
  )
}
